### ISSUE TITLE
Add action to create new certs against CA

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/layer-easyrsa#11]
When plugging in solutions that are not Juju deployed, IE: docker registry, it'd be nice to have an action that produced a cert by the operator against the EasyRSA CA.

**Comment by MadWombat** [comment]
I think this ability might be useful in other use cases as well. For example to use client certs to grant access to the API. Currently it is unclear how to do that with a juju managed kube cluster.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809378.
